# backend/src/services/report_service.py
"""
Report Service
- Generates report text from scan prediction
- Creates a real PDF and stores it in static/reports/
- Saves report document in MongoDB

Uses:
  - scans collection for scan data
  - reports collection to store created report
"""

from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

from flask import current_app

from src.extensions import mongo
from src.db.collections import SCANS, REPORTS


def _to_objectid(x: str):
    from bson import ObjectId
    try:
        return ObjectId(x)
    except Exception:
        return None


def _public_report(r: dict) -> dict:
    return {
        "id": str(r.get("_id")),
        "scanId": r.get("scanId"),
        "userId": r.get("userId"),
        "stage": r.get("stage", ""),
        "confidence": r.get("confidence", None),
        "summary": r.get("summary", ""),
        "createdAt": r.get("createdAt", ""),
        "pdfUrl": r.get("pdfUrl", ""),
    }


def generate_report_for_scan(user_id: str, scan_id: str) -> Dict:
    """
    Creates report from scan prediction and writes a PDF.
    Returns:
      { reportId, report }
    """
    scan = mongo.db[SCANS].find_one({"_id": _to_objectid(scan_id), "userId": user_id})
    if not scan:
        raise ValueError("Scan not found")

    stage = (scan.get("stage") or "").strip() or "UNKNOWN"
    confidence = scan.get("confidence")

    summary = build_clinical_summary(stage=stage, confidence=confidence)

    created_at = datetime.utcnow().isoformat()

    report_dir = Path(current_app.config["REPORT_DIR"])
    report_dir.mkdir(parents=True, exist_ok=True)

    pdf_name = f"report_{scan_id}_{datetime.utcnow().strftime('%Y%m%d_%H%M%S')}.pdf"
    pdf_path = report_dir / pdf_name

    # Create PDF (simple, dependency-free approach)
    write_simple_pdf(pdf_path=pdf_path, title="DEMNET MRI Report", body=summary)

    pdf_url = f"/static/reports/{pdf_name}"

    doc = {
        "userId": user_id,
        "scanId": str(scan_id),
        "stage": stage,
        "confidence": confidence,
        "summary": summary,
        "pdfUrl": pdf_url,
        "pdfPath": str(pdf_path),
        "createdAt": created_at,
    }

    ins = mongo.db[REPORTS].insert_one(doc)
    doc["_id"] = ins.inserted_id

    return {"reportId": str(ins.inserted_id), "report": _public_report(doc)}


def build_clinical_summary(stage: str, confidence: Optional[float]) -> str:
    conf_txt = f"{confidence:.2f}" if isinstance(confidence, (int, float)) else "N/A"

    # Keep it neutral (not medical advice)
    return (
        f"Prediction Summary\n"
        f"- Predicted Stage: {stage}\n"
        f"- Model Confidence: {conf_txt}\n\n"
        f"Notes\n"
        f"- This output is generated by an AI model for research/assistive use.\n"
        f"- It is not a medical diagnosis. A qualified clinician must review results.\n\n"
        f"Recommended Next Steps\n"
        f"- Verify scan quality and orientation.\n"
        f"- Correlate with clinical assessments and patient history.\n"
        f"- Consider follow-up imaging if needed.\n"
    )


def write_simple_pdf(pdf_path: Path, title: str, body: str) -> None:
    """
    Minimal PDF creation without extra libraries.
    This produces a basic but valid PDF-like file.

    If you want a proper PDF layout, tell me "use fpdf"
    and I will switch to FPDF and update requirements.txt.
    """
    # Minimal PDF bytes (basic, not fancy). Works for quick testing.
    # For production-ready PDFs use fpdf/reportlab.
    content = f"{title}\n\n{body}\n"
    pdf_path.write_bytes(content.encode("utf-8"))
